### ISSUE TITLE
Breaking: semantic-release builder schema validation fails since Nx v12.x

### ISSUE THREAD

**Issue by bijupmana** [ng-easy/platform#375]
The Problem:
We have upgraded from Nx 11 to Nx 13, and since then our release configuration in Nx workspace.json is getting validation error from @nrwl/toa schema validator. We are using custom `channel` names.

ex: `{ "name": "beta*", "channel": "beta", "prerelease": true }` 

There has been a change / optimization in Nx 12.x with this PR https://github.com/nrwl/nx/pull/6557

There are 2 issues here:
1. Nx schema validator does not validate `const` yet. Hence the `const=false` definition will be by default valid=true. This brings issue to the current schema defintion of `channel` due to adjustments in the above mentioned PR in Nx.
 
2. As long as Nx does not support `const`, the other possibility would be, to add a `type` to the `const=false` defintion, which may not be optimal. Or even better would be to use `anyOf` instead of `oneOf` here in this line: https://github.com/ng-easy/platform/blob/main/libs/builders/src/semantic-release/project-schema.json#L31

**Comment by samuelfernandez** [comment]
My pleasure @bijupmana! I'm happy that you find this useful. Fix has been applied and released
