### ISSUE TITLE
fix(builders): rxjs version is outdated, update to v7

### ISSUE THREAD

**Issue by johannesschobel** [ng-easy/platform#487]
Dear @samuelfernandez ,

is it possible to update the peer dependency for `rxjs` from `~6.6.7` to `^7.0.0`?
https://github.com/ng-easy/platform/blob/f61c78fef8c71265cffd2e4a7e41253303fe5154/libs/builders/package.json#L51

New `nrwl/nx` projects with `nest` or other apps currently have set rxjs to `7.0.0`. This does not allow to install `@ng-easy/builders` without errors.

All the best,
Johannes

**Comment by samuelfernandez** [comment]
Sure @johannesschobel! Fixing here #488

**Comment by johannesschobel** [comment]
Thanks a lot!

**Comment by samuelfernandez** [comment]
> 🎉 This issue has been resolved in version **@ng-easy/builders@7.1.0** 🎉
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ng-easy/builders/v/7.1.0) 📦🚀
> * [GitHub release](https://github.com/ng-easy/platform/releases/tag/%40ng-easy/builders%407.1.0) 📦🚀

@johannesschobel released! :)
