### ISSUE TITLE
feat(builders): expose github plugin options on sem rel builder

### ISSUE THREAD

**Issue by javisank** [ng-easy/platform#610]
I am using semantic-release with ng-easy. I wanted to make further configurations to the semantic-release/github plugin (one of many that ng-easy uses under the hood).
My main problem is that I want to set successComment to false to not get every PR commented. Is there any way to config this? Is it hardcoded?
Thanks in advance.

**Comment by samuelfernandez** [comment]
@javisank That is a good idea! I'll work on exposing that configuration through the builder params. Sounds good? Thanks for reaching out! 😃

**Comment by javisank** [comment]
Actually, it sounds great. One question though. Would it work with a semantic-release [configuration file](https://github.com/semantic-release/github#successcomment) as it is now? If it works that way, maybe it is not necessary to change the code, but adding that explanation in the docs.

**Comment by samuelfernandez** [comment]
That is true, undesired, yet can't be changed. As you mention, having a config file can provide some settings. However, in the builder approach that configuration should be passed from the project. Since exposing it in the right way should not be hard I'd prefer that approach

**Comment by javisank** [comment]
This is another question somewhat related. Is there any way, using ng-easy builders, to add a semantic release plugin (I want to add semantic-release-slack-bot), and configure it?

**Comment by samuelfernandez** [comment]
The way the builder works is standing in the middle between Nx and sem rel, so it needs full control. Can't see an easy way to customize externally. Happy to consider as an enhancement

**Comment by samuelfernandez** [comment]
> This is another question somewhat related. Is there any way, using ng-easy builders, to add a semantic release plugin (I want to add semantic-release-slack-bot), and configure it?

Could you report it as a separate issue? Also provide an example configuration to see how it would work
